image: gableroux/unity3d:2020.1.13f1

stages:
  - build_and_test

# If you are looking for a place where to add 'UNITY_LICENSE_FILE' nad secrets, please visit your project's gitlab page:
# settings > CI/CD > Variables instead
variables:
  BUILD_NAME: XR4All_UnityExample
  UNITY_VERSION: 2020.1.13f1
  UNITY_ACTIVATION_FILE: ./Unity_v$UNITY_VERSION.alf

.unity_before_script: &unity_before_script
  before_script:
    - chmod +x ./ci/before_script.sh && ./ci/before_script.sh

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - indebrauVR/Library/

# run this job when you need to request a license
# you may need to follow activation steps from documentation
get-activation-file:
  when: manual
  stage: build_and_test
  script:
    - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
  artifacts:
    paths:
      - $UNITY_ACTIVATION_FILE
    expire_in: 10 min # Expiring this as artifacts may contain sensitive data and should not be kept public

.test: &test
  stage: build_and_test
  <<: *unity_before_script
  <<: *cache
  script:
    - ls
    - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    when: always
    paths:
      - $(pwd)/$TEST_PLATFORM-results.xml
      - $(pwd)/$TEST_PLATFORM-coverage/
  coverage: /<Linecoverage>(.*?)</Linecoverage>/

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode
